apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-cluster-backup
  namespace: velero
spec:
  schedule: "0 1 * * *"
  template:
    ttl: 720h0m0s
    includedNamespaces:
    - "*"
    excludedNamespaces:
    - kube-system
    snapshotVolumes: true
